# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/that-ml-library',
                'doc_host': 'https://anhquan0412.github.io',
                'git_url': 'https://github.com/anhquan0412/that-ml-library',
                'lib_path': 'that_ml_library'},
  'syms': { 'that_ml_library.core': {'that_ml_library.core.foo': ('core.html#foo', 'that_ml_library/core.py')},
            'that_ml_library.data_preprocess': { 'that_ml_library.data_preprocess.one_hot_cat': ( 'data_preprocess.html#one_hot_cat',
                                                                                                  'that_ml_library/data_preprocess.py'),
                                                 'that_ml_library.data_preprocess.preprocessing_general': ( 'data_preprocess.html#preprocessing_general',
                                                                                                            'that_ml_library/data_preprocess.py'),
                                                 'that_ml_library.data_preprocess.process_missing_values': ( 'data_preprocess.html#process_missing_values',
                                                                                                             'that_ml_library/data_preprocess.py'),
                                                 'that_ml_library.data_preprocess.scale_num_cols': ( 'data_preprocess.html#scale_num_cols',
                                                                                                     'that_ml_library/data_preprocess.py')},
            'that_ml_library.utils': {'that_ml_library.utils.val2list': ('utils.html#val2list', 'that_ml_library/utils.py')}}}
