# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/that-ml-library',
                'doc_host': 'https://anhquan0412.github.io',
                'git_url': 'https://github.com/anhquan0412/that-ml-library',
                'lib_path': 'that_ml_library'},
  'syms': {'that_ml_library.core': {'that_ml_library.core.foo': ('core.html#foo', 'that_ml_library/core.py')}}}
