# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['val2list']

# %% ../nbs/00_utils.ipynb 4
def val2list(val,lsize=1):
    "Convert an element (nonlist value) to a list of 1 element"
    if not isinstance(val,list):
        val=[val for i in range(lsize)]
    return val
